name: wget
on: [push]
runs-on: ubuntu-latest
steps:
 - uses: actions/checkout@v2
 - name: Setup Python
 - uses: actions/setup-python@v2
   run: |
    wget -m -p -E -k -np https://gochiusa.com/af/
    python main.py

